# Generated by Django 5.1.3 on 2024-11-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebliotheque', '0002_borrowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
